'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.17929
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace ConfigService
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://Beanland.AutoVer.Config", ConfigurationName:="ConfigService.IConfigEngine")>  _
    Public Interface IConfigEngine
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://Beanland.AutoVer.Config/IConfigEngine/GetUserMesage", ReplyAction:="http://Beanland.AutoVer.Config/IConfigEngine/GetUserMesageResponse")>  _
        Function GetUserMesage() As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://Beanland.AutoVer.Config/IConfigEngine/GetIsService", ReplyAction:="http://Beanland.AutoVer.Config/IConfigEngine/GetIsServiceResponse")>  _
        Function GetIsService() As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://Beanland.AutoVer.Config/IConfigEngine/GetAppConfig", ReplyAction:="http://Beanland.AutoVer.Config/IConfigEngine/GetAppConfigResponse")>  _
        Function GetAppConfig() As System.Collections.Generic.Dictionary(Of Object, Object)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://Beanland.AutoVer.Config/IConfigEngine/GetAppConfigFolder", ReplyAction:="http://Beanland.AutoVer.Config/IConfigEngine/GetAppConfigFolderResponse")>  _
        Function GetAppConfigFolder() As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://Beanland.AutoVer.Config/IConfigEngine/GetConfigFolder", ReplyAction:="http://Beanland.AutoVer.Config/IConfigEngine/GetConfigFolderResponse")>  _
        Function GetConfigFolder() As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://Beanland.AutoVer.Config/IConfigEngine/GetWatcherStatus", ReplyAction:="http://Beanland.AutoVer.Config/IConfigEngine/GetWatcherStatusResponse")>  _
        Function GetWatcherStatus() As AutoVer.WatcherStatus()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://Beanland.AutoVer.Config/IConfigEngine/LoadAppConfig", ReplyAction:="http://Beanland.AutoVer.Config/IConfigEngine/LoadAppConfigResponse")>  _
        Sub LoadAppConfig()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://Beanland.AutoVer.Config/IConfigEngine/SaveAppConfig", ReplyAction:="http://Beanland.AutoVer.Config/IConfigEngine/SaveAppConfigResponse")>  _
        Sub SaveAppConfig()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://Beanland.AutoVer.Config/IConfigEngine/LoadWatcherConfig", ReplyAction:="http://Beanland.AutoVer.Config/IConfigEngine/LoadWatcherConfigResponse")>  _
        Sub LoadWatcherConfig()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://Beanland.AutoVer.Config/IConfigEngine/SaveWatcherConfig", ReplyAction:="http://Beanland.AutoVer.Config/IConfigEngine/SaveWatcherConfigResponse")>  _
        Sub SaveWatcherConfig()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://Beanland.AutoVer.Config/IConfigEngine/UpdateWatchersList", ReplyAction:="http://Beanland.AutoVer.Config/IConfigEngine/UpdateWatchersListResponse")>  _
        Sub UpdateWatchersList()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://Beanland.AutoVer.Config/IConfigEngine/AppConfigDefault", ReplyAction:="http://Beanland.AutoVer.Config/IConfigEngine/AppConfigDefaultResponse")>  _
        Function AppConfigDefault(ByVal Key As String, ByVal DefaultValue As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://Beanland.AutoVer.Config/IConfigEngine/ReloadWatcher", ReplyAction:="http://Beanland.AutoVer.Config/IConfigEngine/ReloadWatcherResponse")>  _
        Sub ReloadWatcher(ByVal watcherId As System.Guid)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://Beanland.AutoVer.Config/IConfigEngine/DeleteWatcher", ReplyAction:="http://Beanland.AutoVer.Config/IConfigEngine/DeleteWatcherResponse")>  _
        Sub DeleteWatcher(ByVal watcherId As System.Guid)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://Beanland.AutoVer.Config/IConfigEngine/PauseWatcher", ReplyAction:="http://Beanland.AutoVer.Config/IConfigEngine/PauseWatcherResponse")>  _
        Sub PauseWatcher(ByVal watcherId As System.Guid)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IConfigEngineChannel
        Inherits ConfigService.IConfigEngine, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ConfigEngineClient
        Inherits System.ServiceModel.ClientBase(Of ConfigService.IConfigEngine)
        Implements ConfigService.IConfigEngine
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function GetUserMesage() As String Implements ConfigService.IConfigEngine.GetUserMesage
            Return MyBase.Channel.GetUserMesage
        End Function
        
        Public Function GetIsService() As Boolean Implements ConfigService.IConfigEngine.GetIsService
            Return MyBase.Channel.GetIsService
        End Function
        
        Public Function GetAppConfig() As System.Collections.Generic.Dictionary(Of Object, Object) Implements ConfigService.IConfigEngine.GetAppConfig
            Return MyBase.Channel.GetAppConfig
        End Function
        
        Public Function GetAppConfigFolder() As String Implements ConfigService.IConfigEngine.GetAppConfigFolder
            Return MyBase.Channel.GetAppConfigFolder
        End Function
        
        Public Function GetConfigFolder() As String Implements ConfigService.IConfigEngine.GetConfigFolder
            Return MyBase.Channel.GetConfigFolder
        End Function
        
        Public Function GetWatcherStatus() As AutoVer.WatcherStatus() Implements ConfigService.IConfigEngine.GetWatcherStatus
            Return MyBase.Channel.GetWatcherStatus
        End Function
        
        Public Sub LoadAppConfig() Implements ConfigService.IConfigEngine.LoadAppConfig
            MyBase.Channel.LoadAppConfig
        End Sub
        
        Public Sub SaveAppConfig() Implements ConfigService.IConfigEngine.SaveAppConfig
            MyBase.Channel.SaveAppConfig
        End Sub
        
        Public Sub LoadWatcherConfig() Implements ConfigService.IConfigEngine.LoadWatcherConfig
            MyBase.Channel.LoadWatcherConfig
        End Sub
        
        Public Sub SaveWatcherConfig() Implements ConfigService.IConfigEngine.SaveWatcherConfig
            MyBase.Channel.SaveWatcherConfig
        End Sub
        
        Public Sub UpdateWatchersList() Implements ConfigService.IConfigEngine.UpdateWatchersList
            MyBase.Channel.UpdateWatchersList
        End Sub
        
        Public Function AppConfigDefault(ByVal Key As String, ByVal DefaultValue As String) As String Implements ConfigService.IConfigEngine.AppConfigDefault
            Return MyBase.Channel.AppConfigDefault(Key, DefaultValue)
        End Function
        
        Public Sub ReloadWatcher(ByVal watcherId As System.Guid) Implements ConfigService.IConfigEngine.ReloadWatcher
            MyBase.Channel.ReloadWatcher(watcherId)
        End Sub
        
        Public Sub DeleteWatcher(ByVal watcherId As System.Guid) Implements ConfigService.IConfigEngine.DeleteWatcher
            MyBase.Channel.DeleteWatcher(watcherId)
        End Sub
        
        Public Sub PauseWatcher(ByVal watcherId As System.Guid) Implements ConfigService.IConfigEngine.PauseWatcher
            MyBase.Channel.PauseWatcher(watcherId)
        End Sub
    End Class
End Namespace
